package dsl.story.storyitem.model.entity;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;

@Entity(indices = {@Index("entryId")},
        foreignKeys = @ForeignKey(entity = Entry.class,
                                  parentColumns = "id",
                                  childColumns = "entryId"))
public class Choice {
    //TODO: Later, make the primary for choice autogenerated. Don't want to add noise in the migration to room
    @PrimaryKey//(autoGenerate = true)
    private int id;
    private int entryId;
    private String text;
    private int nextEntryId;

    public Choice(int id, int entryId, String text, int nextEntryId){
        this.id = id;
        this.entryId = entryId;
        this.text = text;
        this.nextEntryId = nextEntryId;
    }

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public int getEntryId() {
        return entryId;
    }
    public void setEntryId(int entryId) {
        this.entryId = entryId;
    }

    public String getText() {
        return text;
    }
    public void setText(String text) {
        this.text = text;
    }

    public int getNextEntryId() {
        return nextEntryId;
    }
    public void setNextEntryId(int nextEntryId) {
        this.nextEntryId = nextEntryId;
    }
}